name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.39
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: homestead_test
          MYSQL_USER: homestead
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=20s --health-timeout=10s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Verify repository contents
        run: ls -la

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, mysql

      - name: Verify PHP Version
        run: php -v

      - name: Install Composer Dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --no-progress --no-suggest --prefer-dist
          else
            echo "composer.json not found"
            exit 1
          fi

      - name: Create .env file
        run: |
          echo "APP_NAME=LearnBuddy" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=homestead_test" >> .env
          echo "DB_USERNAME=homestead" >> .env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "LOG_CHANNEL=single" >> .env
          echo "FILESYSTEM_DISK=public" >> .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Create storage directories
        run: |
          mkdir -p storage/logs
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/app/public/materials  # Добавлено создание папки для материалов
          chmod -R 775 storage
          php artisan storage:link  # Создаем симлинк для доступа к файлам

      - name: Check MySQL
        run: mysqladmin -u homestead -p${{ secrets.MYSQL_PASSWORD }} -h 127.0.0.1 ping

      - name: Run Migrations
        run: php artisan migrate --database=mysql --verbose || (cat storage/logs/laravel.log && exit 1)

      - name: Run Tests
        run: php artisan test

      - name: Debug test failure
        if: failure()
        run: |
          echo "PHP Version:"
          php -v
          echo "Composer Dependencies:"
          composer show || echo "No composer dependencies"
          echo "Environment Variables:"
          env
          echo "Database Connection Test:"
          mysql -u homestead -p${{ secrets.MYSQL_PASSWORD }} -h 127.0.0.1 -e "SHOW DATABASES;" || echo "Database connection failed"
          echo "Storage Directory Contents:"
          ls -la storage/ || echo "Storage directory not found"
          ls -la storage/logs/ || echo "Logs directory not found"
          ls -la storage/app/public/ || echo "Public storage directory not found"
          ls -la public/storage/ || echo "Storage symlink not found"

      - name: Show test logs on failure
        if: failure()
        run: |
          if [ -f storage/logs/laravel.log ]; then
            cat storage/logs/laravel.log
          else
            echo "Log file storage/logs/laravel.log does not exist."
          fi
