name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: homestead_test
          MYSQL_USER: homestead
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, mysql

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Create .env file
        run: |
          echo "APP_NAME=LearnBuddy" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=homestead_test" >> .env
          echo "DB_USERNAME=homestead" >> .env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "LOG_CHANNEL=single" >> .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Create storage directories
        run: |
          mkdir -p storage/logs
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          chmod -R 775 storage

      - name: Check MySQL
        run: mysqladmin -u homestead -p${{ secrets.MYSQL_PASSWORD }} -h 127.0.0.1 ping

      - name: Run Migrations
        run: php artisan migrate --database=mysql --verbose

      - name: Run Tests
        run: php artisan test

      - name: Debug test failure
        if: failure()
        run: |
          echo "PHP Version:"
          php -v
          echo "Composer Dependencies:"
          composer show
          echo "Environment Variables:"
          env
          echo "Database Connection Test:"
          mysql -u homestead -p${{ secrets.MYSQL_PASSWORD }} -h 127.0.0.1 -e "SHOW DATABASES;"
          echo "Storage Directory Contents:"
          ls -la storage/
          ls -la storage/logs/

      - name: Show test logs on failure
        if: failure()
        run: |
          if [ -f storage/logs/laravel.log ]; then
            cat storage/logs/laravel.log
          else
            echo "Log file storage/logs/laravel.log does not exist."
          fi
